name: Run PHPCS and PHPLint

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PHPCS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Show PHPCS sniffs
        run: npm run phpcs -i

      - name: Show PHPCS version
        run: npm run phpcs --version

      - name: Run PHP_CodeSniffer
        run: npm run phpcs

  PHPLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Show PHPLint version info
        run: npm run phplint --version

      - name: Run PHPLint
        run: npm run phplint
